// Class: ReadMLPBFGS
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLPBFGS
TMVA Release   : 4.1.3         [262403]
ROOT Release   : 5.34/00       [336384]
Creator        : gavrilov
Date           : Wed Aug  7 19:25:07 2013
Host           : Linux okpccms281.cern.ch 2.6.32-279.el6.x86_64 #1 SMP Thu Jun 21 10:37:09 CEST 2012 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/scratch/ZEWKANA/DY_QG
Training events: 65906
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TrainingMethod: "BFGS" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 6
Pt_J                          Pt_J                          Pt_J                          Pt_J                                                            'F'    [50.0001945496,876.135681152]
PTD_J                         PTD_J                         PTD_J                         PTD_J                                                           'F'    [0,1]
rPt_tr                        rPt_tr                        rPt_tr                        rPt_tr                                                          'F'    [-1.99794626236,1.90425264835]
N_tr                          N_tr                          N_tr                          N_tr                                                            'F'    [0,37]
D1_tr                         D1_tr                         D1_tr                         D1_tr                                                           'F'    [-3.46944695195e-18,0.181809857488]
D2_tr                         D2_tr                         D2_tr                         D2_tr                                                           'F'    [-5.87872496781e-17,0.0816779062152]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLPBFGS : public IClassifierReader {

 public:

   // constructor
   ReadMLPBFGS( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLPBFGS" ),
        fNvars( 6 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Pt_J", "PTD_J", "rPt_tr", "N_tr", "D1_tr", "D2_tr" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLPBFGS() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][6];
   double fMax_1[3][6];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[6];
   double fVmax[6];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[6];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[12][7];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][12];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLPBFGS::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 7; fWeights[0] = new double[7]; 
   fLayerSize[1] = 12; fWeights[1] = new double[12]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -1.56359160923239;
   fWeightMatrix0to1[1][0] = -0.738089191538069;
   fWeightMatrix0to1[2][0] = -0.458257248062081;
   fWeightMatrix0to1[3][0] = 0.312111857119943;
   fWeightMatrix0to1[4][0] = -2.16038377788413;
   fWeightMatrix0to1[5][0] = -1.44506884333704;
   fWeightMatrix0to1[6][0] = -2.02969155007278;
   fWeightMatrix0to1[7][0] = 0.715840584672234;
   fWeightMatrix0to1[8][0] = -0.736489795721739;
   fWeightMatrix0to1[9][0] = 0.19511848520408;
   fWeightMatrix0to1[10][0] = -3.13068375470519;
   fWeightMatrix0to1[0][1] = -0.394048688476537;
   fWeightMatrix0to1[1][1] = -0.697228709358389;
   fWeightMatrix0to1[2][1] = 0.565611503400948;
   fWeightMatrix0to1[3][1] = 0.119953423973399;
   fWeightMatrix0to1[4][1] = -0.598677885632;
   fWeightMatrix0to1[5][1] = -0.171552315393392;
   fWeightMatrix0to1[6][1] = -0.463705868901165;
   fWeightMatrix0to1[7][1] = 0.300381163798037;
   fWeightMatrix0to1[8][1] = 1.76966289836582;
   fWeightMatrix0to1[9][1] = 0.519720364183968;
   fWeightMatrix0to1[10][1] = -0.494462550789148;
   fWeightMatrix0to1[0][2] = 0.753299394869914;
   fWeightMatrix0to1[1][2] = 5.38933420289362;
   fWeightMatrix0to1[2][2] = -0.792241881696788;
   fWeightMatrix0to1[3][2] = -1.18459355757239;
   fWeightMatrix0to1[4][2] = 5.39150696197182;
   fWeightMatrix0to1[5][2] = 1.8084083024011;
   fWeightMatrix0to1[6][2] = -1.49112395502911;
   fWeightMatrix0to1[7][2] = 0.127806946880248;
   fWeightMatrix0to1[8][2] = 0.415034349737697;
   fWeightMatrix0to1[9][2] = 1.73835325816539;
   fWeightMatrix0to1[10][2] = -2.30419889186565;
   fWeightMatrix0to1[0][3] = -1.43271796701467;
   fWeightMatrix0to1[1][3] = 0.467268307405435;
   fWeightMatrix0to1[2][3] = -1.37812822339162;
   fWeightMatrix0to1[3][3] = -0.108032997922645;
   fWeightMatrix0to1[4][3] = 3.6445241910353;
   fWeightMatrix0to1[5][3] = -2.86091083896026;
   fWeightMatrix0to1[6][3] = 0.924703059257759;
   fWeightMatrix0to1[7][3] = 1.24634432641395;
   fWeightMatrix0to1[8][3] = -0.461159624753959;
   fWeightMatrix0to1[9][3] = 2.409138262611;
   fWeightMatrix0to1[10][3] = 3.17595771914887;
   fWeightMatrix0to1[0][4] = -0.243751067610326;
   fWeightMatrix0to1[1][4] = -1.91362630013879;
   fWeightMatrix0to1[2][4] = 0.312693032870465;
   fWeightMatrix0to1[3][4] = 0.264431069056199;
   fWeightMatrix0to1[4][4] = 3.05627492334745;
   fWeightMatrix0to1[5][4] = 0.676874009402222;
   fWeightMatrix0to1[6][4] = 3.22651756396053;
   fWeightMatrix0to1[7][4] = 2.35794553891917;
   fWeightMatrix0to1[8][4] = -1.24202499887122;
   fWeightMatrix0to1[9][4] = 1.69811361129355;
   fWeightMatrix0to1[10][4] = 0.568276709202437;
   fWeightMatrix0to1[0][5] = -2.3918980860792;
   fWeightMatrix0to1[1][5] = -4.71233459925312;
   fWeightMatrix0to1[2][5] = -1.44143117875077;
   fWeightMatrix0to1[3][5] = 0.535981385928705;
   fWeightMatrix0to1[4][5] = 0.837263079765616;
   fWeightMatrix0to1[5][5] = -1.11502555143724;
   fWeightMatrix0to1[6][5] = 2.88154583712867;
   fWeightMatrix0to1[7][5] = 0.255018167786661;
   fWeightMatrix0to1[8][5] = 0.949843419655154;
   fWeightMatrix0to1[9][5] = 1.86083902166;
   fWeightMatrix0to1[10][5] = 0.973049842839682;
   fWeightMatrix0to1[0][6] = 2.15205071445499;
   fWeightMatrix0to1[1][6] = -7.53175567220873;
   fWeightMatrix0to1[2][6] = 1.64891501081449;
   fWeightMatrix0to1[3][6] = 0.813384825968417;
   fWeightMatrix0to1[4][6] = 1.29370759893007;
   fWeightMatrix0to1[5][6] = -2.24039339703619;
   fWeightMatrix0to1[6][6] = 2.01056594972202;
   fWeightMatrix0to1[7][6] = 0.285837991967357;
   fWeightMatrix0to1[8][6] = 1.26224034208304;
   fWeightMatrix0to1[9][6] = -1.71003851636941;
   fWeightMatrix0to1[10][6] = 0.137476959497072;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.115483525043381;
   fWeightMatrix1to2[0][1] = 0.263041295436413;
   fWeightMatrix1to2[0][2] = 0.339630411471163;
   fWeightMatrix1to2[0][3] = 1.05141322248154;
   fWeightMatrix1to2[0][4] = 0.212926299243288;
   fWeightMatrix1to2[0][5] = 0.214503767217917;
   fWeightMatrix1to2[0][6] = -0.195905881471373;
   fWeightMatrix1to2[0][7] = -0.18563086031238;
   fWeightMatrix1to2[0][8] = 0.256208541515101;
   fWeightMatrix1to2[0][9] = -0.718131653673095;
   fWeightMatrix1to2[0][10] = -0.318584682275775;
   fWeightMatrix1to2[0][11] = -0.800337511800183;
}

inline double ReadMLPBFGS::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLPBFGS::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLPBFGS::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLPBFGS::Clear() 
{
   // nothing to clear
}
   inline double ReadMLPBFGS::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLPBFGS::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 50.0001945496;
   fMax_1[0][0] = 876.135681152;
   fMin_1[1][0] = 50.001865387;
   fMax_1[1][0] = 704.084960938;
   fMin_1[2][0] = 50.0001945496;
   fMax_1[2][0] = 876.135681152;
   fMin_1[0][1] = 0;
   fMax_1[0][1] = 1;
   fMin_1[1][1] = 0;
   fMax_1[1][1] = 1;
   fMin_1[2][1] = 0;
   fMax_1[2][1] = 1;
   fMin_1[0][2] = -1.99794626236;
   fMax_1[0][2] = 1.90425264835;
   fMin_1[1][2] = -1.87525367737;
   fMax_1[1][2] = 0.817002952099;
   fMin_1[2][2] = -1.99794626236;
   fMax_1[2][2] = 1.90425264835;
   fMin_1[0][3] = 0;
   fMax_1[0][3] = 37;
   fMin_1[1][3] = 0;
   fMax_1[1][3] = 37;
   fMin_1[2][3] = 0;
   fMax_1[2][3] = 37;
   fMin_1[0][4] = -3.46944695195e-18;
   fMax_1[0][4] = 0.181809857488;
   fMin_1[1][4] = 0;
   fMax_1[1][4] = 0.123228564858;
   fMin_1[2][4] = -3.46944695195e-18;
   fMax_1[2][4] = 0.181809857488;
   fMin_1[0][5] = -5.87872496781e-17;
   fMax_1[0][5] = 0.0816779062152;
   fMin_1[1][5] = -1.64798730218e-17;
   fMax_1[1][5] = 0.0399604178965;
   fMin_1[2][5] = -5.87872496781e-17;
   fMax_1[2][5] = 0.0816779062152;
}

//_______________________________________________________________________
inline void ReadMLPBFGS::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 6;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesGet.push_back( 4);
   indicesGet.push_back( 5);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);
   indicesPut.push_back( 4);
   indicesPut.push_back( 5);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<6;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLPBFGS::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLPBFGS::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
