// Class: ReadMLPBNN
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLPBNN
TMVA Release   : 4.1.3         [262403]
ROOT Release   : 5.34/00       [336384]
Creator        : gavrilov
Date           : Sun Oct 27 13:07:43 2013
Host           : Linux okpccms281.cern.ch 2.6.32-279.el6.x86_64 #1 SMP Thu Jun 21 10:37:09 CEST 2012 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/scratch/ZEWKANA/DY_QG
Training events: 34355
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TrainingMethod: "BFGS" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "True" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 5
Pt_J                          Pt_J                          Pt_J                          Pt_J                                                            'F'    [30.0002613068,39.999370575]
PTD_J                         PTD_J                         PTD_J                         PTD_J                                                           'F'    [0,1]
N_tr                          N_tr                          N_tr                          N_tr                                                            'F'    [0,17]
D1_tr                         D1_tr                         D1_tr                         D1_tr                                                           'F'    [-8.67361737988e-19,0.205567970872]
D2_tr                         D2_tr                         D2_tr                         D2_tr                                                           'F'    [-8.55187823128e-17,0.0646337121725]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLPBNN : public IClassifierReader {

 public:

   // constructor
   ReadMLPBNN( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLPBNN" ),
        fNvars( 5 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Pt_J", "PTD_J", "N_tr", "D1_tr", "D2_tr" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 0.99999988079071;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLPBNN() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][5];
   double fMax_1[3][5];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[5];
   double fVmax[5];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[5];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[11][6];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][11];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLPBNN::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 6; fWeights[0] = new double[6]; 
   fLayerSize[1] = 11; fWeights[1] = new double[11]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.0553302966748895;
   fWeightMatrix0to1[1][0] = 0.623619154945575;
   fWeightMatrix0to1[2][0] = 0.606075376322204;
   fWeightMatrix0to1[3][0] = 0.0554473990868434;
   fWeightMatrix0to1[4][0] = 0.0726282425899193;
   fWeightMatrix0to1[5][0] = -0.209616215967211;
   fWeightMatrix0to1[6][0] = -0.612441782443231;
   fWeightMatrix0to1[7][0] = 1.02921720032411;
   fWeightMatrix0to1[8][0] = -0.510508852878884;
   fWeightMatrix0to1[9][0] = 0.0310452435112714;
   fWeightMatrix0to1[0][1] = -0.0830981583739621;
   fWeightMatrix0to1[1][1] = -0.67259988937229;
   fWeightMatrix0to1[2][1] = -0.792731284975522;
   fWeightMatrix0to1[3][1] = -0.0696663872280502;
   fWeightMatrix0to1[4][1] = -0.615023880692482;
   fWeightMatrix0to1[5][1] = 1.16764400288222;
   fWeightMatrix0to1[6][1] = -0.792713760386061;
   fWeightMatrix0to1[7][1] = 1.03104136759904;
   fWeightMatrix0to1[8][1] = 0.157739606818445;
   fWeightMatrix0to1[9][1] = 0.693310534157954;
   fWeightMatrix0to1[0][2] = -0.345457617619135;
   fWeightMatrix0to1[1][2] = -1.19752865294763;
   fWeightMatrix0to1[2][2] = -0.0685169493360548;
   fWeightMatrix0to1[3][2] = 0.347328275812726;
   fWeightMatrix0to1[4][2] = -0.363808477324951;
   fWeightMatrix0to1[5][2] = -0.81719046053703;
   fWeightMatrix0to1[6][2] = 0.865719827289131;
   fWeightMatrix0to1[7][2] = -0.469161540267096;
   fWeightMatrix0to1[8][2] = -1.3345739025143;
   fWeightMatrix0to1[9][2] = 0.168967361405097;
   fWeightMatrix0to1[0][3] = 1.88834195142546;
   fWeightMatrix0to1[1][3] = 0.803267064907801;
   fWeightMatrix0to1[2][3] = -0.259655103941592;
   fWeightMatrix0to1[3][3] = -0.000151069269519601;
   fWeightMatrix0to1[4][3] = -0.980025556808608;
   fWeightMatrix0to1[5][3] = -0.503429828392401;
   fWeightMatrix0to1[6][3] = -0.977449493104245;
   fWeightMatrix0to1[7][3] = 0.63779302536217;
   fWeightMatrix0to1[8][3] = -0.579504267643648;
   fWeightMatrix0to1[9][3] = 2.18402499496437;
   fWeightMatrix0to1[0][4] = 0.514243807142825;
   fWeightMatrix0to1[1][4] = 0.955685773138041;
   fWeightMatrix0to1[2][4] = 1.68216064992641;
   fWeightMatrix0to1[3][4] = 0.474549135309002;
   fWeightMatrix0to1[4][4] = -1.02149498915128;
   fWeightMatrix0to1[5][4] = -0.639923193653694;
   fWeightMatrix0to1[6][4] = 0.772215283010402;
   fWeightMatrix0to1[7][4] = -0.102484330739847;
   fWeightMatrix0to1[8][4] = 0.885826133234424;
   fWeightMatrix0to1[9][4] = 0.818713341823458;
   fWeightMatrix0to1[0][5] = 2.43737294592572;
   fWeightMatrix0to1[1][5] = -0.647467069606992;
   fWeightMatrix0to1[2][5] = -1.74963641181683;
   fWeightMatrix0to1[3][5] = 0.437388981032791;
   fWeightMatrix0to1[4][5] = -2.33236032430205;
   fWeightMatrix0to1[5][5] = -0.936700527161449;
   fWeightMatrix0to1[6][5] = -0.528890258624693;
   fWeightMatrix0to1[7][5] = -1.94376142413118;
   fWeightMatrix0to1[8][5] = 1.53308651267745;
   fWeightMatrix0to1[9][5] = 2.43806561787201;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.959456525860319;
   fWeightMatrix1to2[0][1] = 0.407696058819308;
   fWeightMatrix1to2[0][2] = -0.790957758881199;
   fWeightMatrix1to2[0][3] = 0.593799860513656;
   fWeightMatrix1to2[0][4] = 1.02458378793076;
   fWeightMatrix1to2[0][5] = 0.398641795037709;
   fWeightMatrix1to2[0][6] = -0.0637832500289248;
   fWeightMatrix1to2[0][7] = -0.119512540451453;
   fWeightMatrix1to2[0][8] = 0.0686512878180773;
   fWeightMatrix1to2[0][9] = 0.836527264724396;
   fWeightMatrix1to2[0][10] = 0.942264816109803;
}

inline double ReadMLPBNN::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLPBNN::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLPBNN::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLPBNN::Clear() 
{
   // nothing to clear
}
   inline double ReadMLPBNN::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLPBNN::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 30.0002613068;
   fMax_1[0][0] = 39.999370575;
   fMin_1[1][0] = 30.0019321442;
   fMax_1[1][0] = 39.997592926;
   fMin_1[2][0] = 30.0002613068;
   fMax_1[2][0] = 39.999370575;
   fMin_1[0][1] = 0;
   fMax_1[0][1] = 1;
   fMin_1[1][1] = 0;
   fMax_1[1][1] = 1;
   fMin_1[2][1] = 0;
   fMax_1[2][1] = 1;
   fMin_1[0][2] = 0;
   fMax_1[0][2] = 15;
   fMin_1[1][2] = 0;
   fMax_1[1][2] = 17;
   fMin_1[2][2] = 0;
   fMax_1[2][2] = 17;
   fMin_1[0][3] = -4.33680868994e-19;
   fMax_1[0][3] = 0.205567970872;
   fMin_1[1][3] = -8.67361737988e-19;
   fMax_1[1][3] = 0.188840806484;
   fMin_1[2][3] = -8.67361737988e-19;
   fMax_1[2][3] = 0.205567970872;
   fMin_1[0][4] = -8.55187823128e-17;
   fMax_1[0][4] = 0.0542756095529;
   fMin_1[1][4] = -3.35039448598e-17;
   fMax_1[1][4] = 0.0646337121725;
   fMin_1[2][4] = -8.55187823128e-17;
   fMax_1[2][4] = 0.0646337121725;
}

//_______________________________________________________________________
inline void ReadMLPBNN::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 5;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesGet.push_back( 4);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);
   indicesPut.push_back( 4);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<5;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLPBNN::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLPBNN::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
