// Class: ReadBDTMitFisher
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDTMitFisher
TMVA Release   : 4.1.3         [262403]
ROOT Release   : 5.34/00       [336384]
Creator        : gavrilov
Date           : Sun Aug  4 15:29:10 2013
Host           : Linux okpccms281.cern.ch 2.6.32-279.el6.x86_64 #1 SMP Thu Jun 21 10:37:09 CEST 2012 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/scratch/ZEWKANA/DY_QG
Training events: 348585
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "50" [Number of trees in the forest]
BoostType: "AdaBoost" [Boosting type for the trees in the forest]
AdaBoostBeta: "5.000000e-01" [Parameter for AdaBoost algorithm]
SeparationType: "giniindex" [Separation criterion for node splitting]
nEventsMin: "150" [Minimum number of events required in a leaf node (default: Classification: max(40, N_train/(Nvar^2)/10), Regression: 10)]
nCuts: "20" [Number of steps during node cut optimisation]
UseFisherCuts: "True" [Use multivariate splits using the Fisher criterion]
PruneMethod: "nopruning" [Method used for pruning (removal) of statistically insignificant branches]
MaxDepth: "3" [Max depth of the decision tree allowed]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
RenormByClass: "False" [Individually re-normalize each event class to the original size after boosting]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2t (Linear,Quadratic or Exponential)]
UseBaggedGrad: "False" [Use only a random subsample of all events for growing the trees in each iteration. (Only valid for GradBoost)]
GradBaggingFraction: "6.000000e-01" [Defines the fraction of events to be used in each iteration when UseBaggedGrad=kTRUE. (Only valid for GradBoost)]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
UseRandomisedTrees: "False" [Choose at each node splitting a random set of variables]
UseNvars: "2" [Number of variables used if randomised tree option is chosen]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split]
UseNTrainEvents: "348585" [Number of randomly picked training events used in randomised (and bagged) trees]
UseWeightedTrees: "True" [Use weighted trees or simple average in classification from the forest]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
PruneStrength: "0.000000e+00" [Pruning strength]
PruneBeforeBoost: "False" [Flag to prune the tree before applying boosting algorithm]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
NNodesMax: "100000" [Max number of nodes in tree]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : Ignore;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!); Randomly pair events with negative and positive weights in leaf node and do not boost them (experimental!) ]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 4
Pt_J                          Pt_J                          Pt_J                          Pt_J                                                            'F'    [50.0000534058,1117.47351074]
N_tr                          N_tr                          N_tr                          N_tr                                                            'F'    [0,39]
D1_tr                         D1_tr                         D1_tr                         D1_tr                                                           'F'    [-1.38777878078e-17,0.206915140152]
D2_tr                         D2_tr                         D2_tr                         D2_tr                                                           'F'    [-8.32667268469e-17,0.0628373920918]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTMitFisherNode
   
#ifndef BDTMitFisherNode__def
#define BDTMitFisherNode__def
   
class BDTMitFisherNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTMitFisherNode ( BDTMitFisherNode* left,BDTMitFisherNode* right,
                          int nFisherCoeff,
                          double fisherCoeff0,
                          double fisherCoeff1,
                          double fisherCoeff2,
                          double fisherCoeff3,
                          double fisherCoeff4,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fNFisherCoeff ( nFisherCoeff ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
     fFisherCoeff.push_back(fisherCoeff0);
     fFisherCoeff.push_back(fisherCoeff1);
     fFisherCoeff.push_back(fisherCoeff2);
     fFisherCoeff.push_back(fisherCoeff3);
     fFisherCoeff.push_back(fisherCoeff4);
   }

   virtual ~BDTMitFisherNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTMitFisherNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTMitFisherNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTMitFisherNode*   fLeft;     // pointer to the left daughter node
   BDTMitFisherNode*   fRight;    // pointer to the right daughter node
   int                     fNFisherCoeff; // =0 if this node doesn use fisher, else =nvar+1 
   std::vector<double>     fFisherCoeff;  // the fisher coeff (offset at the last element)
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTMitFisherNode::~BDTMitFisherNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTMitFisherNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
   if (fNFisherCoeff == 0){
     result = (inputValues[fSelector] > fCutValue );
   }else{
     double fisher = fFisherCoeff.at(fFisherCoeff.size()-1);
     for (unsigned int ivar=0; ivar<fFisherCoeff.size()-1; ivar++)
       fisher += fFisherCoeff.at(ivar)*inputValues.at(ivar);
     result = fisher > fCutValue;
   }
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTMitFisherNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDTMitFisher : public IClassifierReader {

 public:

   // constructor
   ReadBDTMitFisher( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDTMitFisher" ),
        fNvars( 4 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Pt_J", "N_tr", "D1_tr", "D2_tr" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 50.0000534057617;
      fVmax[0] = 1117.47351074219;
      fVmin[1] = 0;
      fVmax[1] = 39;
      fVmin[2] = -1.38777878078145e-17;
      fVmax[2] = 0.206915140151978;
      fVmin[3] = -8.32667268468867e-17;
      fVmax[3] = 0.0628373920917511;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDTMitFisher() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[4];
   double fVmax[4];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[4];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTMitFisherNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDTMitFisher::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTMitFisherNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTMitFisherNode*)current->GetRight();
         else current=(BDTMitFisherNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDTMitFisher::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.637103883152566);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.600568,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.464979,-99) , 
0, 0, 0, 0, 0, 0, 1, 12.7619, 0, 0, 0.515122,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 13.2857, 0, -1, 0.285298,-99) , 
0, 0, 0, 0, 0, 0, 3, 0.00239785, 0, 0, 0.46198,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0.00299226, 0, -1, 0.161501,-99) , 
0, 0, 0, 0, 0, 0, 1, 9.28571, 0, 0, 0.231943,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.415658);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.590784,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.470797,-99) , 
0, 0, 0, 0, 0, 0, 0, 77.6195, 1, 0, 0.535529,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.514363,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.309416,-99) , 
0, 0, 0, 0, 0, 0, 1, 11.5714, 0, 0, 0.345996,-99) , 
0, 0, 0, 0, 0, 0, 3, 0.00238096, 0, 0, 0.482826,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0.00299226, 0, -1, 0.20823,-99) , 
0, 0, 0, 0, 0, 0, 1, 7.42857, 0, 0, 0.337268,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.291292);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.566914,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.466724,-99) , 
0, 0, 0, 0, 0, 0, 1, 9.14286, 0, 0, 0.510023,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0.0012665, 0, -1, 0.325302,-99) , 
0, 0, 0, 0, 0, 0, 2, 0.00690506, 0, 0, 0.456542,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0.0098531, 0, -1, 0.201793,-99) , 
0, 0, 0, 0, 0, 0, 1, 5.57143, 0, 0, 0.388446,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.231504);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.547948,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.432977,-99) , 
0, 0, 0, 0, 0, 0, 1, 12.2857, 1, 0, 0.528091,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0.000904546, 0, -1, 0.399492,-99) , 
0, 0, 0, 0, 0, 0, 3, 0.00237212, 0, 0, 0.484058,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0.0098531, 0, -1, 0.252781,-99) , 
0, 0, 0, 0, 0, 0, 1, 5.57143, 0, 0, 0.425155,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.152243);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.645018,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.497207,-99) , 
0, 0, 0, 0, 0, 0, 1, 17, 0, 0, 0.500462,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.552973,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.369648,-99) , 
0, 0, 0, 0, 0, 0, 1, 9.28571, 0, 0, 0.422305,-99) , 
0, 0, 0, 0, 0, 0, 2, 0.00690506, 0, 0, 0.47865,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0.0098531, 0, -1, 0.298944,-99) , 
0, 0, 0, 0, 0, 0, 1, 5.57143, 0, 0, 0.434328,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.155714);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.542736,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.457198,-99) , 
0, 0, 0, 0, 0, 0, 0, 138.195, 1, 0, 0.53681,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0.00095024, 0, -1, 0.437442,-99) , 
0, 0, 0, 0, 0, 0, 2, 0.00690506, 0, 0, 0.50939,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0.0098531, 0, -1, 0.331793,-99) , 
0, 0, 0, 0, 0, 0, 1, 5.57143, 0, 0, 0.466433,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.0863849);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 19, 0, 1, 0.506895,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0.000701253, 0, -1, 0.43398,-99) , 
0, 0, 0, 0, 0, 0, 2, 0.00771844, 0, 0, 0.480893,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 73.9486, 1, -1, 0.255187,-99) , 
0, 0, 0, 0, 0, 0, 1, 3.71429, 0, 0, 0.465169,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.0860235);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.629186,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.485444,-99) , 
0, 0, 0, 0, 0, 0, 1, 17, 0, 0, 0.48812,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 84.6042, 1, -1, 0.413335,-99) , 
0, 0, 0, 0, 0, 0, 1, 5.66667, 0, 0, 0.474642,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 73.9486, 1, -1, 0.27195,-99) , 
0, 0, 0, 0, 0, 0, 1, 3.71429, 0, 0, 0.460768,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.0639424);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 15.4286, 0, 1, 0.508825,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 84.6042, 1, -1, 0.434339,-99) , 
0, 0, 0, 0, 0, 0, 1, 5.66667, 0, 0, 0.495467,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 73.9486, 1, -1, 0.289312,-99) , 
0, 0, 0, 0, 0, 0, 1, 3.71429, 0, 0, 0.481581,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.0903547);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.532835,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.479542,-99) , 
0, 0, 0, 0, 0, 0, 0, 59.6823, 1, 0, 0.497245,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.50789,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.274249,-99) , 
0, 0, 0, 0, 0, 0, 1, 7.33333, 0, 0, 0.446743,-99) , 
0, 0, 0, 0, 0, 0, 0, 100.832, 1, 0, 0.4852,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 73.9486, 1, -1, 0.302634,-99) , 
0, 0, 0, 0, 0, 0, 1, 3.71429, 0, 0, 0.473044,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.0760374);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.516541,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.482764,-99) , 
0, 0, 0, 0, 0, 0, 1, 6.19048, 0, 0, 0.504832,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 7.33333, 0, -1, 0.435608,-99) , 
0, 0, 0, 0, 0, 0, 0, 100.832, 1, 0, 0.488368,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 73.9486, 1, -1, 0.322036,-99) , 
0, 0, 0, 0, 0, 0, 1, 3.71429, 0, 0, 0.477446,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.056116);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.503981,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.427555,-99) , 
0, 0, 0, 0, 0, 0, 1, 12.7619, 1, 0, 0.499003,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.504311,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.308577,-99) , 
0, 0, 0, 0, 0, 0, 1, 7.33333, 0, 0, 0.454385,-99) , 
0, 0, 0, 0, 0, 0, 0, 100.832, 1, 0, 0.488421,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 73.9486, 1, -1, 0.338857,-99) , 
0, 0, 0, 0, 0, 0, 1, 3.71429, 0, 0, 0.478704,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.0642147);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 12.7619, 1, -1, 0.486799,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.505883,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.378744,-99) , 
0, 0, 0, 0, 0, 0, 1, 9, 0, 0, 0.447361,-99) , 
0, 0, 0, 0, 0, 0, 0, 100.832, 1, 0, 0.477462,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 73.9486, 1, -1, 0.35154,-99) , 
0, 0, 0, 0, 0, 0, 1, 3.71429, 0, 0, 0.469343,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.053716);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.506005,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.457229,-99) , 
0, 0, 0, 0, 0, 0, 1, 12.7619, 1, 0, 0.502849,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 7.33333, 0, -1, 0.445882,-99) , 
0, 0, 0, 0, 0, 0, 0, 100.832, 1, 0, 0.489393,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.509664,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.37967,-99) , 
0, 0, 0, 0, 0, 0, 2, 0.00786321, 0, 0, 0.427547,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 96.7584, 1, -1, 0.22442,-99) , 
0, 0, 0, 0, 0, 0, 0, 73.9486, 1, 0, 0.366314,-99) , 
0, 0, 0, 0, 0, 0, 1, 3.71429, 0, 0, 0.481517,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.0532652);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.512268,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.484037,-99) , 
0, 0, 0, 0, 0, 0, 0, 54.841, 1, 0, 0.488176,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 9, 0, -1, 0.426558,-99) , 
0, 0, 0, 0, 0, 0, 0, 151.664, 1, 0, 0.48362,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 73.9486, 1, -1, 0.371878,-99) , 
0, 0, 0, 0, 0, 0, 1, 3.71429, 0, 0, 0.476512,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.0381623);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0.00881929, 1, 1, 0.58122,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 151.664, 1, -1, 0.490215,-99) , 
0, 0, 0, 0, 0, 0, 1, 15.6667, 0, 0, 0.493311,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.509551,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.40517,-99) , 
0, 0, 0, 0, 0, 0, 2, 0.00786321, 0, 0, 0.443894,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 96.7584, 1, -1, 0.243588,-99) , 
0, 0, 0, 0, 0, 0, 0, 73.9486, 1, 0, 0.384402,-99) , 
0, 0, 0, 0, 0, 0, 1, 3.71429, 0, 0, 0.486421,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.0428083);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.513438,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.492286,-99) , 
0, 0, 0, 0, 0, 0, 1, 6.47619, 0, 0, 0.506719,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.505507,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.325112,-99) , 
0, 0, 0, 0, 0, 0, 1, 9, 0, 0, 0.445253,-99) , 
0, 0, 0, 0, 0, 0, 0, 151.664, 1, 0, 0.502202,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 73.9486, 1, -1, 0.388453,-99) , 
0, 0, 0, 0, 0, 0, 1, 3.71429, 0, 0, 0.495034,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.0336729);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.505876,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.482756,-99) , 
0, 0, 0, 0, 0, 0, 0, 108.092, 1, 0, 0.502818,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 9, 0, -1, 0.441545,-99) , 
0, 0, 0, 0, 0, 0, 0, 151.664, 1, 0, 0.498325,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.500857,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.401831,-99) , 
0, 0, 0, 0, 0, 0, 0, 59.1228, 1, 0, 0.456827,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 96.7584, 1, -1, 0.258815,-99) , 
0, 0, 0, 0, 0, 0, 0, 73.9486, 1, 0, 0.398669,-99) , 
0, 0, 0, 0, 0, 0, 1, 3.71429, 0, 0, 0.492069,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.0334645);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0.00881929, 1, 1, 0.564537,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 151.664, 1, -1, 0.490699,-99) , 
0, 0, 0, 0, 0, 0, 1, 15.6667, 0, 0, 0.493203,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 73.9486, 1, -1, 0.40014,-99) , 
0, 0, 0, 0, 0, 0, 1, 3.71429, 0, 0, 0.487377,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.0280071);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.51312,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.499511,-99) , 
0, 0, 0, 0, 0, 0, 0, 79.0458, 0, 0, 0.504638,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.50672,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.349683,-99) , 
0, 0, 0, 0, 0, 0, 1, 9, 0, 0, 0.454835,-99) , 
0, 0, 0, 0, 0, 0, 0, 151.664, 1, 0, 0.501001,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 73.9486, 1, -1, 0.408199,-99) , 
0, 0, 0, 0, 0, 0, 1, 3.71429, 0, 0, 0.495208,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0281776);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 64.5229, 1, 1, 0.506365,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 9, 0, -1, 0.452388,-99) , 
0, 0, 0, 0, 0, 0, 0, 151.664, 1, 0, 0.502428,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 73.9486, 1, -1, 0.414982,-99) , 
0, 0, 0, 0, 0, 0, 1, 3.71429, 0, 0, 0.496981,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.0193006);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0.00983541, 1, 1, 0.65739,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.500056,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.439552,-99) , 
0, 0, 0, 0, 0, 0, 1, 4.7619, 0, 0, 0.495684,-99) , 
0, 0, 0, 0, 0, 0, 1, 20.6667, 0, 0, 0.496411,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 73.9486, 1, -1, 0.421838,-99) , 
0, 0, 0, 0, 0, 0, 1, 3.71429, 0, 0, 0.491775,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0399068);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.507463,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.482924,-99) , 
0, 0, 0, 0, 0, 0, 1, 7.95238, 1, 0, 0.495871,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.506289,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.359128,-99) , 
0, 0, 0, 0, 0, 0, 1, 7.28571, 0, 0, 0.467461,-99) , 
0, 0, 0, 0, 0, 0, 0, 100.832, 1, 0, 0.489435,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 66.954, 1, -1, 0.273019,-99) , 
0, 0, 0, 0, 0, 0, 1, 1.85714, 0, 0, 0.488199,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0365934);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.509516,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.491525,-99) , 
0, 0, 0, 0, 0, 0, 2, 0.0154103, 0, 0, 0.498171,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 9, 0, -1, 0.468311,-99) , 
0, 0, 0, 0, 0, 0, 0, 100.832, 1, 0, 0.491175,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 73.9486, 1, -1, 0.420082,-99) , 
0, 0, 0, 0, 0, 0, 1, 3.71429, 0, 0, 0.48676,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0205039);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.50085,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.486558,-99) , 
0, 0, 0, 0, 0, 0, 0, 98.4096, 1, 0, 0.498133,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.50111,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.366521,-99) , 
0, 0, 0, 0, 0, 0, 1, 9, 0, 0, 0.457068,-99) , 
0, 0, 0, 0, 0, 0, 0, 151.664, 1, 0, 0.495145,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 73.9486, 1, -1, 0.429022,-99) , 
0, 0, 0, 0, 0, 0, 1, 3.71429, 0, 0, 0.491049,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0302637);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0.00980633, 1, 1, 0.537717,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 151.664, 1, -1, 0.48715,-99) , 
0, 0, 0, 0, 0, 0, 1, 14.3333, 0, 0, 0.489582,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 66.954, 1, -1, 0.29269,-99) , 
0, 0, 0, 0, 0, 0, 1, 1.85714, 0, 0, 0.488479,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0293012);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.506195,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.45505,-99) , 
0, 0, 0, 0, 0, 0, 1, 4.66667, 0, 0, 0.499507,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 7.28571, 0, -1, 0.455092,-99) , 
0, 0, 0, 0, 0, 0, 0, 151.664, 1, 0, 0.496418,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 66.954, 1, -1, 0.298995,-99) , 
0, 0, 0, 0, 0, 0, 1, 1.85714, 0, 0, 0.495319,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0211963);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0.00939467, 1, 1, 0.615357,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 4.42857, 0, -1, 0.491104,-99) , 
0, 0, 0, 0, 0, 0, 1, 19.619, 0, 0, 0.491891,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 66.954, 1, -1, 0.305172,-99) , 
0, 0, 0, 0, 0, 0, 1, 1.85714, 0, 0, 0.490858,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0221552);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.503598,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.464274,-99) , 
0, 0, 0, 0, 0, 0, 1, 4.95238, 0, 0, 0.498621,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.56509,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.383737,-99) , 
0, 0, 0, 0, 0, 0, 1, 14.3333, 0, 0, 0.441366,-99) , 
0, 0, 0, 0, 0, 0, 0, 202.496, 1, 0, 0.497122,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 66.954, 1, -1, 0.309685,-99) , 
0, 0, 0, 0, 0, 0, 1, 1.85714, 0, 0, 0.496089,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.018311);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0.00939467, 1, 1, 0.605046,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 202.496, 1, -1, 0.492435,-99) , 
0, 0, 0, 0, 0, 0, 1, 19.619, 0, 0, 0.493145,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 66.954, 1, -1, 0.314441,-99) , 
0, 0, 0, 0, 0, 0, 1, 1.85714, 0, 0, 0.492164,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0158214);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.502596,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.474353,-99) , 
0, 0, 0, 0, 0, 0, 1, 4.95238, 0, 0, 0.499026,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.505889,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.33566,-99) , 
0, 0, 0, 0, 0, 0, 3, 0.00104876, 0, 0, 0.446878,-99) , 
0, 0, 0, 0, 0, 0, 0, 202.496, 1, 0, 0.497665,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 66.954, 1, -1, 0.318402,-99) , 
0, 0, 0, 0, 0, 0, 1, 1.85714, 0, 0, 0.496683,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.0148057);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0.00939467, 1, 1, 0.59695,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 202.496, 1, -1, 0.494108,-99) , 
0, 0, 0, 0, 0, 0, 1, 19.619, 0, 0, 0.494755,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 66.954, 1, -1, 0.321845,-99) , 
0, 0, 0, 0, 0, 0, 1, 1.85714, 0, 0, 0.493811,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0132909);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.502249,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.480904,-99) , 
0, 0, 0, 0, 0, 0, 0, 117.775, 1, 0, 0.499265,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.537154,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.34766,-99) , 
0, 0, 0, 0, 0, 0, 1, 14.3333, 0, 0, 0.419814,-99) , 
0, 0, 0, 0, 0, 0, 0, 253.328, 1, 0, 0.498409,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 66.954, 1, -1, 0.325085,-99) , 
0, 0, 0, 0, 0, 0, 1, 1.85714, 0, 0, 0.497465,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0138057);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.548151,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.495899,-99) , 
0, 0, 0, 0, 0, 0, 1, 16.0952, 0, 0, 0.496871,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.533848,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.35068,-99) , 
0, 0, 0, 0, 0, 0, 1, 14.3333, 0, 0, 0.420492,-99) , 
0, 0, 0, 0, 0, 0, 0, 253.328, 1, 0, 0.49605,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 66.954, 1, -1, 0.328008,-99) , 
0, 0, 0, 0, 0, 0, 1, 1.85714, 0, 0, 0.495137,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0167818);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.507284,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.494185,-99) , 
0, 0, 0, 0, 0, 0, 0, 69.3644, 1, 0, 0.500194,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.530411,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.35383,-99) , 
0, 0, 0, 0, 0, 0, 1, 14.3333, 0, 0, 0.421198,-99) , 
0, 0, 0, 0, 0, 0, 0, 253.328, 1, 0, 0.499346,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 66.954, 1, -1, 0.331058,-99) , 
0, 0, 0, 0, 0, 0, 1, 1.85714, 0, 0, 0.498433,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0145431);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.51382,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.49689,-99) , 
0, 0, 0, 0, 0, 0, 1, 10.8095, 0, 0, 0.50054,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.526229,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.357677,-99) , 
0, 0, 0, 0, 0, 0, 1, 14.3333, 0, 0, 0.422059,-99) , 
0, 0, 0, 0, 0, 0, 0, 253.328, 1, 0, 0.499698,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 66.954, 1, -1, 0.334785,-99) , 
0, 0, 0, 0, 0, 0, 1, 1.85714, 0, 0, 0.498807,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0088936);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 19.619, 0, 1, 0.502608,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.522602,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.361025,-99) , 
0, 0, 0, 0, 0, 0, 1, 14.3333, 0, 0, 0.422807,-99) , 
0, 0, 0, 0, 0, 0, 0, 253.328, 1, 0, 0.501753,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 66.954, 1, -1, 0.338032,-99) , 
0, 0, 0, 0, 0, 0, 1, 1.85714, 0, 0, 0.50087,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.00462946);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.589029,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.499953,-99) , 
0, 0, 0, 0, 0, 0, 1, 19.619, 0, 0, 0.500385,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.520383,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.363079,-99) , 
0, 0, 0, 0, 0, 0, 1, 14.3333, 0, 0, 0.423265,-99) , 
0, 0, 0, 0, 0, 0, 0, 253.328, 1, 0, 0.499559,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 66.954, 1, -1, 0.340025,-99) , 
0, 0, 0, 0, 0, 0, 1, 1.85714, 0, 0, 0.4987,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.00666538);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 19.619, 0, 1, 0.501531,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.519227,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.36415,-99) , 
0, 0, 0, 0, 0, 0, 1, 14.3333, 0, 0, 0.423505,-99) , 
0, 0, 0, 0, 0, 0, 0, 253.328, 1, 0, 0.500696,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 66.954, 1, -1, 0.341064,-99) , 
0, 0, 0, 0, 0, 0, 1, 1.85714, 0, 0, 0.499837,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.00522292);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.586292,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.499444,-99) , 
0, 0, 0, 0, 0, 0, 1, 19.619, 0, 0, 0.499865,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 5.52381, 0, -1, 0.423849,-99) , 
0, 0, 0, 0, 0, 0, 0, 253.328, 1, 0, 0.499052,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 66.954, 1, -1, 0.342564,-99) , 
0, 0, 0, 0, 0, 0, 1, 1.85714, 0, 0, 0.49821,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.00905007);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.502099,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.463842,-99) , 
0, 0, 0, 0, 0, 0, 0, 185.55, 1, 0, 0.501158,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 5.52381, 0, -1, 0.425125,-99) , 
0, 0, 0, 0, 0, 0, 0, 253.328, 1, 0, 0.500345,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 66.954, 1, -1, 0.343741,-99) , 
0, 0, 0, 0, 0, 0, 1, 1.85714, 0, 0, 0.499504,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.00675862);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.584279,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.498592,-99) , 
0, 0, 0, 0, 0, 0, 1, 19.619, 0, 0, 0.499007,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 5.52381, 0, -1, 0.427338,-99) , 
0, 0, 0, 0, 0, 0, 0, 253.328, 1, 0, 0.498241,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 66.954, 1, -1, 0.345786,-99) , 
0, 0, 0, 0, 0, 0, 1, 1.85714, 0, 0, 0.497423,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.00448287);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 19.619, 0, 1, 0.50068,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 5.52381, 0, -1, 0.428993,-99) , 
0, 0, 0, 0, 0, 0, 0, 253.328, 1, 0, 0.499914,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 66.954, 1, -1, 0.347316,-99) , 
0, 0, 0, 0, 0, 0, 1, 1.85714, 0, 0, 0.499097,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.00552788);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.581545,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.499161,-99) , 
0, 0, 0, 0, 0, 0, 1, 19.619, 0, 0, 0.499559,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 5.52381, 0, -1, 0.430091,-99) , 
0, 0, 0, 0, 0, 0, 0, 253.328, 1, 0, 0.498818,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 66.954, 1, -1, 0.348333,-99) , 
0, 0, 0, 0, 0, 0, 1, 1.85714, 0, 0, 0.498012,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.0048909);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 16.0952, 0, 1, 0.500928,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 5.52381, 0, -1, 0.431447,-99) , 
0, 0, 0, 0, 0, 0, 0, 253.328, 1, 0, 0.500187,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 66.954, 1, -1, 0.349589,-99) , 
0, 0, 0, 0, 0, 0, 1, 1.85714, 0, 0, 0.499381,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0065362);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.540048,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.498941,-99) , 
0, 0, 0, 0, 0, 0, 1, 16.0952, 0, 0, 0.499705,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 5.52381, 0, -1, 0.432647,-99) , 
0, 0, 0, 0, 0, 0, 0, 253.328, 1, 0, 0.49899,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 66.954, 1, -1, 0.350702,-99) , 
0, 0, 0, 0, 0, 0, 1, 1.85714, 0, 0, 0.498197,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.00863333);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.502129,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.467498,-99) , 
0, 0, 0, 0, 0, 0, 0, 185.55, 1, 0, 0.501278,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 5.52381, 0, -1, 0.434252,-99) , 
0, 0, 0, 0, 0, 0, 0, 253.328, 1, 0, 0.500564,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 66.954, 1, -1, 0.352192,-99) , 
0, 0, 0, 0, 0, 0, 1, 1.85714, 0, 0, 0.499771,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.00538757);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0.0159934, 1, 1, 0.689892,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 253.328, 1, -1, 0.498313,-99) , 
0, 0, 0, 0, 0, 0, 1, 23.1429, 0, 0, 0.498556,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 66.954, 1, -1, 0.354164,-99) , 
0, 0, 0, 0, 0, 0, 1, 1.85714, 0, 0, 0.497786,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0043546);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0.0159934, 1, 1, 0.688738,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.500422,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.425645,-99) , 
0, 0, 0, 0, 0, 0, 0, 253.328, 1, 0, 0.49966,-99) , 
0, 0, 0, 0, 0, 0, 1, 23.1429, 0, 0, 0.4999,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 66.954, 1, -1, 0.355397,-99) , 
0, 0, 0, 0, 0, 0, 1, 1.85714, 0, 0, 0.499129,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.00525216);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 23.619, 0, 1, 0.626071,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 253.328, 1, -1, 0.498477,-99) , 
0, 0, 0, 0, 0, 0, 1, 21.381, 0, 0, 0.498833,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, -1, 66.954, 1, -1, 0.356395,-99) , 
0, 0, 0, 0, 0, 0, 1, 1.85714, 0, 0, 0.498074,-99)    );
   return;
};
 
// Clean up
inline void ReadBDTMitFisher::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDTMitFisher::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
